### ISSUE TITLE
Popup for method parameters is fully red

### ISSUE THREAD

**Issue by graynk** [vuesion/intellij-theme#1]
Hey there, thank you for the great theme. 
I'm using latest IntelliJ Idea, and the popup for method parameters is fully red, both background and foreground apparently. Same issue in other JetBrains IDE. Example below.

![image](https://user-images.githubusercontent.com/3626328/56346983-bb9f7600-61dc-11e9-8b58-6b9196e60a0c.png)

This is the reason, I'm presuming:

https://github.com/vuesion/intellij-theme/blob/15773778da4f9e34a91fb8a04dd9f50776331833/resources/META-INF/vuesion_theme.theme.json#L154-L155

**Comment by devCrossNet** [comment]
Nice catch, I will update the theme asap 👍

**Comment by devCrossNet** [comment]
@graynk what do you think about that? (I hope I got the popup you mean)

<img width="619" alt="Bildschirmfoto 2019-04-18 um 12 12 08" src="https://user-images.githubusercontent.com/1667598/56354124-48453680-61d3-11e9-9c7c-b815b577a0af.png">

**Comment by graynk** [comment]
> @graynk what do you think about that? (I hope I got the popup you mean)
> 
> <img alt="Bildschirmfoto 2019-04-18 um 12 12 08" width="619" src="https://user-images.githubusercontent.com/1667598/56354124-48453680-61d3-11e9-9c7c-b815b577a0af.png">

Yup, that looks great

**Comment by devCrossNet** [comment]
I uploaded the new plugin, now we have to wait for verification. Thank you very much!

**Comment by devCrossNet** [comment]
@graynk update is now available

**Comment by graynk** [comment]
> @graynk update is now available

Thank you for the quick fix. Might I also suggest that warnings be indicated with different colour, closer to yellow? Right now errors are bright red and warnings are pastel red which may be confusing at a first glance (more so on non-IPS matrices, I imagine).

Here's a file with two warnings and one error, for example
![image](https://user-images.githubusercontent.com/3626328/56409694-a89bad00-6293-11e9-952d-0a03c0ed146a.png)

**Comment by devCrossNet** [comment]
There is a lot to optimize, thx for pointing this out. It’s my first theme, I still need to learn 👍

**Comment by devCrossNet** [comment]
@graynk and please feel free to contribute 🙂👍
