### ISSUE TITLE
Submenu background

### ISSUE THREAD

**Issue by Arkuda** [vuesion/intellij-theme#10]
For example - when Android Studio show menu to smart suggest and when try to select item, dont have bg for selected item

Visualisation: 

When vueson theme 
![https://sun9-69.userapi.com/c855624/v855624863/12b312/ds7jWn7xDPk.jpg](https://sun9-69.userapi.com/c855624/v855624863/12b312/ds7jWn7xDPk.jpg)

When use other themes 
![https://sun9-69.userapi.com/c854120/v854120863/12a53f/v3BnEzZ26xA.jpg](https://sun9-69.userapi.com/c854120/v854120863/12a53f/v3BnEzZ26xA.jpg)

OS: mac os 10.15
Android Studio 3.5.1
Vueson 1.6

**Comment by KeironLowe** [comment]
I'm having the same issue, makes it difficult to know which option is highlighted, you either have to count in your head how many times you've moved or just press enter and hope for the best.

**Comment by devCrossNet** [comment]
@Arkuda @KeironLowe Sorry, I totally forgot about this. I will have a look the upcoming weekend. I find this annoying by myself.

**Comment by KeironLowe** [comment]
No need to be sorry, thanks for the quick reply, absolutely love the theme by the way!

**Comment by devCrossNet** [comment]
@Arkuda @KeironLowe, here are 3 versions. which one would you go for?

<img width="1092" alt="Bildschirmfoto 2020-07-18 um 17 13 12" src="https://user-images.githubusercontent.com/1667598/87855676-13fe7f80-c91a-11ea-94c3-0f125fd940ae.png">
<img width="1064" alt="Bildschirmfoto 2020-07-18 um 17 12 24" src="https://user-images.githubusercontent.com/1667598/87855679-14971600-c91a-11ea-8f3b-5e163028b46e.png">
<img width="1031" alt="Bildschirmfoto 2020-07-18 um 17 11 52" src="https://user-images.githubusercontent.com/1667598/87855681-152fac80-c91a-11ea-828b-f8527cf9cf9f.png">

**Comment by devCrossNet** [comment]
some more variations
<img width="748" alt="Bildschirmfoto 2020-07-18 um 17 49 57" src="https://user-images.githubusercontent.com/1667598/87856383-20d1a200-c91f-11ea-936b-dc66aef70ed3.png">
<img width="705" alt="Bildschirmfoto 2020-07-18 um 17 48 30" src="https://user-images.githubusercontent.com/1667598/87856384-216a3880-c91f-11ea-8dbc-cef3a402c7f6.png">
<img width="663" alt="Bildschirmfoto 2020-07-18 um 17 46 46" src="https://user-images.githubusercontent.com/1667598/87856385-2202cf00-c91f-11ea-8a7a-f566718720a2.png">

**Comment by KeironLowe** [comment]
I think I'd probably go with the last one, dark grey.

**Comment by devCrossNet** [comment]
Update is on its way:
<img width="1066" alt="Bildschirmfoto 2020-07-26 um 16 48 56" src="https://user-images.githubusercontent.com/1667598/88482175-f48dd500-cf5f-11ea-913f-d3270df49631.png">

**Comment by KeironLowe** [comment]
Just got the update, thanks!
