### ISSUE TITLE
Scrollbars are confusing. Please consider changing the hover color.

### ISSUE THREAD

**Issue by nerdpad** [vuesion/intellij-theme#11]
When you hover over the scrollbars, it gets confusing because of the entire scrollbar being the same color.

Please consider changing the scrollbar color (Maybe the gorgeous pink?)

Normal:
![image](https://user-images.githubusercontent.com/87896/83754220-99172900-a639-11ea-9416-17c5bdd13067.png)

Hover:
![image](https://user-images.githubusercontent.com/87896/83754249-a59b8180-a639-11ea-873e-c0be3496d06f.png)

**Comment by devCrossNet** [comment]
@nerdpad thanks for reporting. I think that is an issue on windows. I will try to reproduce it. on OSX the scrollbars are completely hidden untill you scroll so it's not that confusing.

**Comment by devCrossNet** [comment]
@nerdpad here are a couple of version, which one would you like?

<img width="92" alt="Bildschirmfoto 2020-07-18 um 17 24 16" src="https://user-images.githubusercontent.com/1667598/87855892-9e93ae80-c91b-11ea-9cd6-d18494a9a69c.png">
<img width="113" alt="Bildschirmfoto 2020-07-18 um 17 23 54" src="https://user-images.githubusercontent.com/1667598/87855893-9f2c4500-c91b-11ea-82aa-6ba83dd37144.png">
<img width="91" alt="Bildschirmfoto 2020-07-18 um 17 23 32" src="https://user-images.githubusercontent.com/1667598/87855894-9fc4db80-c91b-11ea-8911-d60ab68acbfa.png">
<img width="94" alt="Bildschirmfoto 2020-07-18 um 17 23 11" src="https://user-images.githubusercontent.com/1667598/87855895-a05d7200-c91b-11ea-988a-1df2205e91f0.png">
<img width="110" alt="Bildschirmfoto 2020-07-18 um 17 22 43" src="https://user-images.githubusercontent.com/1667598/87855896-a05d7200-c91b-11ea-98de-edbcd2a76693.png">

**Comment by devCrossNet** [comment]
<img width="71" alt="Bildschirmfoto 2020-07-18 um 17 27 21" src="https://user-images.githubusercontent.com/1667598/87855945-f3372980-c91b-11ea-8636-1ebc6cc43d11.png">

**Comment by devCrossNet** [comment]
Update is on its way:
<img width="1066" alt="Bildschirmfoto 2020-07-26 um 16 48 56" src="https://user-images.githubusercontent.com/1667598/88482194-0c655900-cf60-11ea-9cf7-d976809d425f.png">
