### ISSUE TITLE
Availability for VS Code 

### ISSUE THREAD

**Issue by ankushduacodes** [vuesion/intellij-theme#12]
Please make this available for VS Code.

**Comment by devCrossNet** [comment]
@ankushduacodes unfortunately, I don't use VS Code and I am not familiar with their theming-system. I can assist if you already know how to do theming for VS Code and I can also provide you with a repository in the vuesion organization.

**Comment by ankushduacodes** [comment]
@devCrossNet I have never developed VS Code myself either.
How about I look into it and reach out to you when I have  done some research into it. I am interested in learning how to make one for VS code

How does that sound?

**Comment by devCrossNet** [comment]
@ankushduacodes that sounds great 👍 

I'll create a repository so we can collaborate as soon as we know how to start this project 🥳 

And let's use this issue to share our findings!

**Comment by devCrossNet** [comment]
maybe, we can even maintain it in this repo. depends a little bit on how the project structure of a vs code theme looks like and how it gets deployed/added to the marketplace.

**Comment by ankushduacodes** [comment]
I will look into it more and let you know within a couple of weeks(this late because I may have my final exams soon)

**Comment by devCrossNet** [comment]
Good luck with the finals! 😃

**Comment by devCrossNet** [comment]
https://css-tricks.com/creating-a-vs-code-theme/

**Comment by devCrossNet** [comment]
I initialized the repo here: https://github.com/vuesion/vscode-theme

That's how far I got so far:
<img width="1314" alt="Bildschirmfoto 2021-01-16 um 19 15 18" src="https://user-images.githubusercontent.com/1667598/104819708-8d2a5100-582f-11eb-8ed2-7feff8f10a46.png">

colors are based on https://vuesion.herokuapp.com/storybook/?path=/story/design-system-branding--1-color-palette

**Comment by ankushduacodes** [comment]
Looking great so far!... Thank you for starting the repo. As soon as my exams finish I will start working on it.

**Comment by ankushduacodes** [comment]
@devCrossNet Have you committed these changes because I am not able to see any syntax highlighting
![Screenshot 2021-01-18 at 5 27 41 PM](https://user-images.githubusercontent.com/61025943/104912599-79f3be80-59b2-11eb-96d2-536086e07df5.png)

**Comment by devCrossNet** [comment]
yes, as you can see here: https://github.com/vuesion/vscode-theme/blob/main/themes/vuesion-color-theme.json

but maybe I didn't include the color tokens that are present in your js file, yet. I only tested a vue-single-file component so far

**Comment by devCrossNet** [comment]
instructions on how to figure out the right color tokens are here: https://github.com/vuesion/vscode-theme/blob/main/vsc-extension-quickstart.md#get-up-and-running-straight-away

**Comment by ankushduacodes** [comment]
I also tried it with a simple vue file but still there was no syntax highlighting.

**Comment by ankushduacodes** [comment]
I may be missing something I will try to see whats going on tomorrow

**Comment by devCrossNet** [comment]
mhhh...maybe the stuff I did doesn't work. maybe, you'll figure it out by playing around with it.

**Comment by devCrossNet** [comment]
here you go: https://marketplace.visualstudio.com/items?itemName=vuesion.vuesion-theme
