### ISSUE TITLE
Code completion dropdown selection is invisible

### ISSUE THREAD

**Issue by brokenthorn** [vuesion/intellij-theme#2]
I just installed the extension and even restarted but I noticed that code completion dropdowns don't seem to have a selection background.

<img width="570" alt="image" src="https://user-images.githubusercontent.com/2119004/61699114-f3b9d600-ad42-11e9-8e3f-f3bf5868b8b8.png">

**Comment by devCrossNet** [comment]
@brokenthorn I just realized that. I have an older version of webstorm on another machine without this issue. Is it correct that you run webstorm 2019.2?

**Comment by devCrossNet** [comment]
<img width="557" alt="Bildschirmfoto 2019-07-23 um 12 52 38" src="https://user-images.githubusercontent.com/1667598/61706618-d0922500-ad48-11e9-8d29-f55b1077fe9a.png">

I will publish the new version of the plugin asap

**Comment by devCrossNet** [comment]
@brokenthorn I am still not happy with the fix. I reached out to JetBrains for help: https://twitter.com/_jwerner_/status/1153774699828195338?s=21

**Comment by brokenthorn** [comment]
> @brokenthorn I just realized that. I have an older version of webstorm on another machine without this issue. Is it correct that you run webstorm 2019.2?

Yes. Thanks for fixing this small issue. I see it was quite a hefty fix though...

**Comment by devCrossNet** [comment]
@brokenthorn Yeah, they changed a couple of things in IDEA 2019.2 so I had to adapt. I am still waiting for the verification of version 1.7 which fixes the issue completely + I changed the looks of the tabs a little bit
