### ISSUE TITLE
Very low text contrast on a light background in the autoimport suggestion tooltip

### ISSUE THREAD

**Issue by brokenthorn** [vuesion/intellij-theme#3]
Hi,

There is a low contrast issue with the autoimport suggestion where the suggestion's text is colored light grey and the suggestion's background is colored light blue, which makes the text very hard to read. Otherwise the theme overall is highly contrasted, while this suggestion popup is not only of low contrast but very unlike the theme's look & feel:

<img width="596" alt="image" src="https://user-images.githubusercontent.com/2119004/61912393-a906ac80-af42-11e9-88b7-6be9dfbc23f6.png">

I suggest you use the same background color as the color used to highlight list selections, like for example as used in the project tool window. That would look something like this:

<img width="596" alt="image" src="https://user-images.githubusercontent.com/2119004/61912934-339bdb80-af44-11e9-80eb-60db4b54b24d.png">

**Comment by devCrossNet** [comment]
Can you tell me how I can see this control? maybe, I never saw it and therefore didn't tweak it.

**Comment by devCrossNet** [comment]
@brokenthorn btw. feel free to create a PR if you know how to change it already

**Comment by devCrossNet** [comment]
And thank you for your help to improve this theme! 😊

**Comment by brokenthorn** [comment]
I really can't afford it right now. Too busy. If you can't fixed it at the moment, yeah, maybe, but later.

The popup appears when you write a valid identifier that is not defined in the current scope (can be imported). You usually press `ENTER` right after writing such an identifer or just before finishing typing all the letters because the IDE shows a drop down automatically with possible auto-completions and pressing `ENTER` chooses the first item. But if you don't do this and just type the whole identifer then use the mouse arrow or the keyboard to place the cursor somewhere else, the IDE keeps re-popping up this info about the identifer, right above it.

Here's a demo:

![PopupSuggestion](https://user-images.githubusercontent.com/2119004/61940523-493def00-af9e-11e9-9395-0d9fa67a29e3.gif)

**Comment by devCrossNet** [comment]
@brokenthorn I am able to reproduce it. I will let you know when it's fixed 👍 Thanks

**Comment by devCrossNet** [comment]
I think I got it: 
<img width="833" alt="Bildschirmfoto 2019-07-26 um 11 54 56" src="https://user-images.githubusercontent.com/1667598/61943734-6a054500-af9c-11e9-8b7f-f84f0143b863.png">

will publish the new version asap 👍
