### ISSUE TITLE
Identify active and unfocused tabs in unfocused view groups

### ISSUE THREAD

**Issue by brokenthorn** [vuesion/intellij-theme#4]
I've identified another small UX issue. Currently, if multiple view groups are open and each have more than one tab open, it's impossible to tell which tab is being displayed, only the currently active tab has a light blue line under it.

![image](https://user-images.githubusercontent.com/2119004/62244583-67fe1480-b3e8-11e9-8554-55b19be41970.png)

**Comment by devCrossNet** [comment]
@brokenthorn nice catch 👍 

I hope it's not a blocker for you, I will try to find some time this weekend to fix it

**Comment by brokenthorn** [comment]
Hardly a blocker. I just seem to have accomodated to your theme lately but being a 1-man made theme, it's bound to have some issues here and there. I'm amazed at how good it is actually. Almost perfect.
