### ISSUE TITLE
Improve TODO syntax colors

### ISSUE THREAD

**Issue by brokenthorn** [vuesion/intellij-theme#5]
JetBrains IDEs have built in "// TODO" and "// FIXME" highlighting as well as customisable "TODO keywords":

![image](https://user-images.githubusercontent.com/2119004/62563073-e1838000-b88a-11e9-8309-a690bb0883e9.png)

The defaults are just two keywords: TODO and FIXME. They both are set  to use the color scheme default TODO colors:

![image](https://user-images.githubusercontent.com/2119004/62563201-2d362980-b88b-11e9-806b-7dda3ebcc8b3.png)

The issue I'm reporting is that vuesion's **default** TODO colors are not visible enough:

![image](https://user-images.githubusercontent.com/2119004/62563537-e72d9580-b88b-11e9-99e6-8deab1423aab.png)

The desired look for me is something resembling this:

![image](https://user-images.githubusercontent.com/2119004/62564064-ea755100-b88c-11e9-9136-95bbc5cba953.png)

If there are any "Vue" colors that are a bit more vibrant, normal weighted text could work too.
Above is bold.

Or some variation on the current colors (TODO set brightness 100%, FIXME set brightness 100%, HUE to 0):

![image](https://user-images.githubusercontent.com/2119004/62564510-aafb3480-b88d-11e9-97d3-e2335db82461.png)

**Comment by devCrossNet** [comment]
Hey, here are all available colors: https://vuesion.herokuapp.com/storybook/?path=/story/design-system-branding--1-color-palette

**Comment by brokenthorn** [comment]
In that case, how does this look:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/2119004/63838190-8fafb080-c985-11e9-891d-2675a3f88a1f.png">

"WARN" is not a default TODO keyword. I added that myself, but if the color scheme can specify these default colors, I guess the TODO color can be replace with the WARN color used in the example (because it's a bit brigther).

As I understand, color schemes can specify default TODO colors, so can you set these defaults?

**Comment by devCrossNet** [comment]
looks great 👍 

I don't have much time at the moment - I'll work on it asap, or you can create a PR

**Comment by brokenthorn** [comment]
Any idea how to get a current build of the plugin and install it with IntelliJ, for testing purposes? Something simple, if possible.

**Comment by devCrossNet** [comment]
hey @brokenthorn,
the easiest way I found so far is to create a new IntelliJ project and copy the contents of this repository into it. Here is the tutorial on how to do it: http://www.jetbrains.org/intellij/sdk/docs/reference_guide/ui_themes/themes.html

From then on if you open the theme file `vuesion_theme.theme.json`, you have a run button on the upper left which applies the whole theme to the IntelliJ IDE.

I didn't find a way so far to just check out this project and run it

**Comment by brokenthorn** [comment]
I was really hoping you'd come back saying you had a way you could release beta builds that can be downloaded from here. ^_^

**Comment by devCrossNet** [comment]
update it uploaded and I am waiting for approval: https://plugins.jetbrains.com/plugin/12226-vuesion-theme/update/69760

I think we can close this now? @brokenthorn

**Comment by brokenthorn** [comment]
Link goes to 404 page.

**Comment by devCrossNet** [comment]
not for me 🤔 

anyway, the new version is published: https://plugins.jetbrains.com/plugin/12226-vuesion-theme
