### ISSUE TITLE
invalid Issues

### ISSUE THREAD

**Issue by eldicn** [vuesion/intellij-theme#7]
invalid Issues

**Comment by devCrossNet** [comment]
@plain-dev I will try to reproduce this issue next week and try to find a fix for it 👍 I never used the theme in Android Studio, maybe there are differences. Can you tell me the version of your IDE?

**Comment by plain-dev** [comment]
@devCrossNet 😄Thanks, the IDE I am using is` IntelliJ IDEA`, the version is `2019.2.1 (Ultimate Edition)`.

**Comment by devCrossNet** [comment]
@plain-dev I am not able to reproduce this issue in my intellij IDE. can you tell me the steps to get there?

**Comment by plain-dev** [comment]
@devCrossNet Open an android project with idea and then open the layout file XML. On the `preview` page on the right, you can see that the colors and themes are not consistent.

**Comment by plain-dev** [comment]
@devCrossNet I found a magical thing, the theme is normal in Android Studio.
The test results are as follows.

|   Screenshot   | ![](https://gitee.com/plain-dev/oss/raw/master/upic_library/BkyZgy.png) | ![](https://gitee.com/plain-dev/oss/raw/master/upic_library/QItUpA.png) |
| :------------: | :----------------------------------------------------------: | :----------------------------------------------------------: |
| Plugin version | ![](https://gitee.com/plain-dev/oss/raw/master/upic_library/xgXSlH.png) | ![](https://gitee.com/plain-dev/oss/raw/master/upic_library/iTVvOj.png) |
|  IDE version   |                    intellij idea 2019.2.3                    |                      Android Studio 3.5                      |
