### ISSUE TITLE
No contrast when selecting items in code completion

### ISSUE THREAD

**Issue by vitality82** [vuesion/intellij-theme#9]
Not sure if related to the theme (was not happening before I started using Vuesion). 
Basically a frustrating issue which results in selecting the wrong code completion every now and then due to not having contrast in the code completion dropdown:

_IDE: Intellij IDEA Ultimate 2019.2.3_
![2019-10-03_13-19-27](https://user-images.githubusercontent.com/3256598/66122959-47695b00-e5e1-11e9-9012-8213ff2ce269.png)

I would expect at least some contrast, not to mention the code completion feature is a first-class citizen in Intellij Idea.

Hopefully, this is low hanging fruit.
Thanks!

**Comment by vitality82** [comment]
IDE: Intellij IDEA Ultimate 2019.2.3

**Comment by devCrossNet** [comment]
That's what it looks in the development version of this theme:

<img width="650" alt="Bildschirmfoto 2019-10-03 um 22 31 20" src="https://user-images.githubusercontent.com/1667598/66161905-8fae6a80-e62d-11e9-8a5c-c0ad85b08bc1.png">

<img width="702" alt="Bildschirmfoto 2019-10-03 um 22 32 56" src="https://user-images.githubusercontent.com/1667598/66162012-ca180780-e62d-11e9-8fc9-ca40a62e1e1a.png">

**Comment by vitality82** [comment]
It does contrast indeed correctly. My color-scheme settings were using vuesion-theme settings, but within the Appearance & Behavior settings there was another theme active (One Dark vivid..).

My apologies.

**Comment by devCrossNet** [comment]
ok, I close this issue then
